spring.application.name=user-service
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/demo_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

management.tracing.sampling.probability=1.0
management.tracing.export.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.access-expiration=604800000

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
spring.kafka.properties.schema.registry.url=http://localhost:8010



management.opentelemetry.tracing.export.otlp.enabled=true
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.opentelemetry.tracing.export.otlp.transport=http

spring.kafka.listener.observation-enabled=true
spring.kafka.template.observation-enabled=true

app.seed.admin.phone-number=${APP_SEED_ADMIN_PHONE_NUMBER:}
app.seed.admin.password=${APP_SEED_ADMIN_PASSWORD:}