spring.application.name=wallet-service

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5434/demo_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.root = ${LOG_LEVEL:info}
#logging.structured.format.console=logstash
logging.structured.format.file=ecs
logging.file.name=./wallet/logs/application.log


spring.web.error.include-message=${SPRING_ERROR_INCLUDE_MESSAGE:always}
spring.web.error.include-stacktrace=${SPRING_ERROR_INCLUDE_STACKTRACE:always}
spring.web.error.include-binding-errors=${SPRING_ERROR_INCLUDE_BINDING_ERRORS:always}


# Spring Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}

# Server Configuration
server.port=${SERVER_PORT:8081}

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=${REDIS_TIMEOUT:2000ms}
spring.data.redis.lettuce.pool.max-active=${REDIS_POOL_MAX_ACTIVE:8}
spring.data.redis.lettuce.pool.max-idle=${REDIS_POOL_MAX_IDLE:8}
spring.data.redis.lettuce.pool.min-idle=${REDIS_POOL_MIN_IDLE:0}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=wallet-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.value-deserializer=io.confluent.kafka.serializers.KafkaAvroDeserializer
spring.kafka.properties.schema.registry.url=${SCHEMA_REGISTRY_URL:http://localhost:8010}
spring.kafka.consumer.properties.specific.avro.reader=true
spring.kafka.listener.observation-enabled=${KAFKA_LISTENER_OBSERVATION_ENABLED:true}
spring.kafka.template.observation-enabled=${KAFKA_TEMPLATE_OBSERVATION_ENABLED:true}

app.wallet.outbox.aggregate-type=wallet
app.wallet.outbox.withdraw.success-topic=withdraw-success
app.wallet.outbox.withdraw.failed-topic=withdraw-failed



management.opentelemetry.tracing.export.otlp.enabled=${OTLP_ENABLED:true}
management.opentelemetry.tracing.export.otlp.endpoint=${OTLP_ENDPOINT:http://localhost:4318/v1/traces}
management.opentelemetry.tracing.export.otlp.transport=${OTLP_TRANSPORT:http}
